# 30. Marginal Crop Land

## Flag

The marginal crop land BMP is flagged using **marginal_crop_land_simulation** in **marginal_crop_land** section. This BMP will be used if it's set to YES. The default value is NO. One example is given below.

*\[marginal_crop_land\]*

*marginal_crop_land_simulation = YES*

## Location

Marginal crop lands could be defined by users or created with specified criteria.

### User-defined

The user-defined marginal crop land shapefile could be specified using **marginal_crop_shapefile** in the **marginal_crop_land** section. One example is given below.

*\[marginal_crop_land\]*

*marginal_crop_shapefile = marginal_crop.shp*

### System-generated

If the user doesn't specify the marginal crop land location, the system generates the location using three parameters.

-   **marginal_crop_land_non_agriculture_landuse_ids**: the area with specified ids will be used as the base for the marginal crop land. Multiple ids should be separated with comma, e.g. 10, 11, 12.

-   **marginal_crop_land_buffer_size_m**: a buffer size from the base area with a default value of 100 m.

-   **marginal_crop_land_slope_threshold_percentage**: slope criteria. Areas with smaller slope will be removed. The default value is 7%.

## Grass Type

The grass type applied to marginal crop lands is specified using **marginal_crop_land_grass_type** section in **marginal_crop_land** section. One example is given below. The default crop, fertilizer and tillage management data of the specified grass type will be applied to all marginal crop lands.

*\[marginal_crop_land\]*

*marginal_crop_land_grass_type = 36*