# 41. WASCob

WASCOB (Water and Sediment Control Basin) blocks water from drainage area. The ponded water drains through tile drain system. It always work with the tile drain system.

## Required Inputs

WASCOB point shapefile is the only input. It specifies the location of the wascob which usually the intercection of the berm and the overland drainage. It's not neccessary that the point falls exatcly on the drainage path. The system will snap the point to the delineated streams.

WASCOB shapefile must have 14 data fields as shown below. The name must match the ones given below.

1.  **id** - unique ids

2.  **StartYear**- the year wascob beomes effective.

3.  **StartMon**- the month wascob beomes effective.

4.  **StartDay**- the day wascob beomes effective.

5.  **BermElev** - berm cres elevation in m

6.  **DeadV**- the dead volume of the ponding area in 10^4^ m^3^

7.  **DeadA**- the dead surface area of the ponding aera in ha

8.  **NormalV**- the normal volume of the ponding area in 10^4^ m^3^

9.  **NormalA**- the normal surface area of the ponding aera in ha

10. **MaxV**- the max volume of the ponding area in 10^4^ m^3^

11. **MaxA**- the max surface area of the ponding aera in ha

12. **MaxQ**- the discharge capacity in m^3^/day.

13. **FieldID**- the corresponding field

14. **TdrainID** - the corresponding tile drain

## Configuration Setup

In the model configuration file, set wascob_outlet_shapefile to the name of the wascob point shapefile.

```         
wascob_shapefile = wascob.shp
```

## Validation

1.  wascob is a point shapefile.

2.  id column is included in the shapefile and has unique values.

3.  The tile drain bmp is present and the tile drain id presents in the tile drain shapefile.

4.  All required columns are available in the shapefile.

## Processing Steps

1.  Use wascob as pour point during watershed delineation

2.  Generate drainage area raster which is essentially the corresponding subbasin.

3.  Generate wascob parameter table. To determine the outlet reach id:

    1.  Find the corresponding [tile drain](19_tiledrain.qmd) field based on tile drain id.

    2.  Find the outlet reach for the identified tile drain field and use it for the wacob.

4.  Add wascob drainage area raster to parameter.h5