# Crop Management

Crop management BMPs specifies the crop rotation, fertilizer application, tillage and gazing on a field. As this data is highly customized, it's usually prepared manually and imported to bmp database.

AAFC crop inventory provides crop distribution each year based on remote sensing technology. Combined with default crop rotation, fertilizer application, tillage and gazing fro crop type, it's possible to setup the crop management BMPs automatically. To use this feature, setup the crop_rotation section in the model configuration file in crop_rotation section. The setting items are given below.

-   **method** - the only option now is crop_inventory.

-   **AAFC_crop_inventory_folder** - the folder the crop inventory GeoTIFF files reside. The file name must be the year, e.g. 2025.tif.

-   **first_year** - the starting year of inventory data to read.

-   **last_year** - the ending year of inventory data to read.

-   **include_grazing** - the flag for grazing generation. By default it's false.

One example is given below.

```         
[crop_rotation]
method = crop_inventory
AAFC_crop_inventory_folder = C:\Work\Git\imWEBs\imWEBs-Python\notebooks\stc\data\crop_inventory 
first_year = 1991
last_year = 2010
include_grazing = False
```

Users will need to download the crop inventory data for the years they are interested and clipped to the watershed boundary. It's also required to have same coordination system as other input files.