from sqlalchemy import Column, Integer, Float, String
from .parameter_table import ParameterTable


class CropParameter(ParameterTable):
    __tablename__ = 'crop_parameter'
    ICNUM = Column(Float, primary_key=True)
    CPNM = Column(String)
    DESCRIPTION = Column(String)
    IDC = Column(Float)
    BIO_E = Column(Float)
    HVSTI = Column(Float)
    BLAI = Column(Float)
    FRGRW1 = Column(Float)
    LAIMX1 = Column(Float)
    FRGRW2 = Column(Float)
    LAIMX2 = Column(Float)
    DLAI = Column(Float)
    CHTMX = Column(Float)
    RDMX = Column(Float)
    T_OPT = Column(Float)
    T_BASE = Column(Float)
    CNYLD = Column(Float)
    CPYLD = Column(Float)
    BN1 = Column(Float)
    BN2 = Column(Float)
    BN3 = Column(Float)
    BP1 = Column(Float)
    BP2 = Column(Float)
    BP3 = Column(Float)
    WSYF = Column(Float)
    USLE_C = Column(Float)
    GSI = Column(Float)
    VPDFR = Column(Float)
    FRGMAX = Column(Float)
    WAVP = Column(Float)
    CO2HI = Column(Float)
    BIOEHI = Column(Float)
    RSDCO_PL = Column(Float)
    OV_N = Column(Float)
    CN2A = Column(Float)
    CN2B = Column(Float)
    CN2C = Column(Float)
    CN2D = Column(Float)
    FERTFIELD = Column(Float)
    ALAI_MIN = Column(Float)
    BIO_LEAF = Column(Float)
    PHU = Column(Float)
    CNOP = Column(Float)
    LAI_INIT = Column(Float)
    BIO_INIT = Column(Float)
    CURYR_INIT = Column(Float)